language: java

services:
  - mongodb
  - docker

before_script:
  - mongo mydb_test --eval 'db.createUser({user:"devwarrior",pwd:"mongodb",roles:["readWrite"]});'
  - docker-compose up

branches:
  only:
  - desenvolvimento

sudo: false
dist: trusty
addons:
  sonarcloud:
    organization: "lucasbsrs-github"
    token:
      secure: 5qhmJz1skfSnHTnp5ia6dQ # encrypted value of your token
before_install:
  - chmod +x mvnw
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  #- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - ./mvnw test -B
